<a href="https://colab.research.google.com/github/San-desh17/Numpy/blob/numpy/Numpy_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#### Numpy array vs Python List

In [6]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]
c = []
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

3.5974528789520264


In [7]:
# numpy
a = np.arange(10000000)
b = np.arange(10000000, 20000000)
start = time.time()
c = a + b
print(time.time() - start)

0.0449376106262207


In [9]:
times = 3.5974528789520264/0.0449376106262207
print(times)

80.05438715633323


In [10]:
# memory
# list

a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [13]:
# numpy
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

#### Advanced Indexing

In [14]:
# Normal indexing and slicing


In [18]:
# Fancy indexing
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
a[[2,3]][:,[3,4]]

array([[13, 14],
       [18, 19]])

In [23]:
a[:,[3,4]]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [24]:
# Boolean Indexing
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
a>10 # boolean array

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [31]:
# boolean sanga kaam garda bitwise operator use garne
a[(a<10) & (a>15)]

array([], dtype=int64)

In [32]:
a[(a<10) | (a>15)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 16, 17, 18, 19])

### Broadcasting

- describes how numpy treats arrays with different shapes during arithmetic operations
- the smaller array is broadcast across the larger array so that they have compatible shapes

In [37]:
# same shape
a = np.arange(20).reshape(4,5)
b = np.arange(20,40).reshape(4,5)
print(a.shape)
print(b.shape)
c = a+b
print(c.shape)

(4, 5)
(4, 5)
(4, 5)


In [38]:
# diff shape
a = np.arange(20).reshape(4,5)
b = np.arange(5)
print(a.shape)
print(b.shape)
c = a+b
print(c.shape)

(4, 5)
(5,)
(4, 5)


#### Broadcasting rules

1.  make thetwo arrays have the same number of dimensions
  - if the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

2. make each dimension of the two arrays the same size
  - if the sizes of eac dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other.
  - if there is a imesion whoes size is not 1 in either of the two arrays, it cannot be broadcasted and an error is raised.


In [35]:
a = np.arange(20).reshape(4,5)
b = np.arange(5)
print(a.shape)
print(b.shape)
c = a+b
print(c.shape)

(4, 5)
(5,)
(4, 5)


In [36]:
print(a)
print(b)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[0 1 2 3 4]
[[ 0  2  4  6  8]
 [ 5  7  9 11 13]
 [10 12 14 16 18]
 [15 17 19 21 23]]


In [39]:
a = np.arange(20).reshape(4,5)
b = np.arange(4).reshape(4,1)
print(a.shape)
print(b.shape)
c = a+b
print(c.shape)

(4, 5)
(4, 1)
(4, 5)


In [40]:
a = np.arange(20).reshape(4,5)
b = np.arange(4)
print(a.shape)
print(b.shape)
c = a+b
print(c.shape)

(4, 5)
(4,)


ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [41]:
a = np.arange(12).reshape(4,3)
b = np.arange(12).reshape(3,4)
print(a.shape)
print(b.shape)
c = a+b
print(c.shape)

(4, 3)
(3, 4)


ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

### Working with mathematical formulas

In [45]:
# sigmoid
def sigmoid(x):
    return 1/(1+np.exp(-x))



In [46]:
a = np.array([1,2,3])
sigmoid(a)

array([0.73105858, 0.88079708, 0.95257413])

In [49]:
# mean squared error
a = np.array([1,2,3])
b = np.array([2,2,3])
def mse(y_true,y_pred):
    return np.mean(np.square(y_true-y_pred))

In [50]:
mse(a,b)

0.3333333333333333

In [51]:
# categorical cross entropy
def categorical_cross_entropy(y_true,y_pred):
    return -np.mean(y_true*np.log(y_pred))
categorical_cross_entropy(a,b)

-1.7917594692280552

### Working with missing values

In [52]:
# working with missing values -> np.nan
a = np.array([1,2,3,np.nan,5])
a

array([ 1.,  2.,  3., nan,  5.])

In [55]:
a[~np.isnan(a)]

array([1., 2., 3., 5.])

### Plotting Graphs