<a href="https://colab.research.google.com/github/San-desh17/Numpy/blob/numpy/Numpy_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is Numpy?

- fundamental package for scientific computing in python.
- provides multidimensional array object, various derived objects (masked array and matrices) and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selectiong, I/O, discrete fourier transforms, basic linear algebra, basic statistical operations, random simulation.
- ndarray object
- homogeneous data types

### Numpy array vs Python sequence

- fixed size at creation vs grow dynamically
- homo vs hetero


#### Creating numpy arrays

In [3]:
# import numpy
import numpy as np

In [2]:
# np.array
a= np.array([1,2,3])

In [3]:
type(a)

numpy.ndarray

In [5]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b.ndim)
print(c.ndim)

2
3


In [6]:
# dtype
a = np.array([1,2,3], dtype=float)
a

array([1., 2., 3.])

In [7]:
# np.arange
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [10]:
# np.ones
a = np.ones((3,4),dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
# np.zeros
a = np.zeros((3,4),dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
# with reshape
a = a.reshape(2,6)
a

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [4]:
# np.random
a = np.random.random((2,3))
a

array([[0.6419275 , 0.4961441 , 0.95112852],
       [0.01322446, 0.34532038, 0.30082081]])

In [6]:
# np.linspace
a = np.linspace(1,100,10)
a

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [7]:
# np.identity
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Array attributes

In [12]:
a = np.arange(10)
b = np.arange(12,dtype=float).reshape(3,4)
c = np.arange(8).reshape(2,2,2)

In [13]:
# ndim
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [14]:
# shape
print(a.shape)
print(b.shape)
print(c.shape)

(10,)
(3, 4)
(2, 2, 2)


In [15]:
# size
print(a.size)
print(b.size)
print(c.size)

10
12
8


In [16]:
# dtype
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
float64
int64


In [18]:
# itemsize
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

8
8
8


#### Changing datatypes

In [19]:
# astype
print(a.dtype)
a = a.astype(np.float32)
print(a.dtype)

int64
float32


#### Array operations

In [24]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


##### Scalar operations

In [23]:
# arithmetic (all)
a-1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [25]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [26]:
b/2

array([[ 6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5]])

In [27]:
# relational (all)
a>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

##### Vector operations

In [29]:
# arithmetic (shape same, all)
a+b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [30]:
# relational (all)
b>a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#### Array functions

In [39]:
# max
a.max()

11

In [41]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.max(a,axis=0) # column

array([ 8,  9, 10, 11])

In [42]:
a.min(axis=1) # row

array([0, 4, 8])

In [44]:
# min
np.min(a)

0

In [45]:
# sum
np.sum(a)

66

In [46]:
# prod
np.prod(a)

0

In [47]:
# mean
np.mean(a,axis=0)

array([4., 5., 6., 7.])

In [48]:
# median
np.median(a)

5.5

In [49]:
# std
np.std(a,axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [50]:
# var
np.var(a,axis=0)

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

##### Trigonometric function

In [56]:
# sine
a = np.sin(a)

In [52]:
# dot product
a.dot(b.transpose())

array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

In [53]:
a.dot(b)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [54]:
# log
np.log(a)

<ipython-input-54-fa1ce51216ff>:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [55]:
# exponential
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [57]:
a

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [61]:
# round
np.round(a)

array([[ 0.,  1.,  1.,  0.],
       [-1., -1., -0.,  1.],
       [ 1.,  0., -1., -1.]])

In [62]:
# floor
np.floor(a)

array([[ 0.,  0.,  0.,  0.],
       [-1., -1., -1.,  0.],
       [ 0.,  0., -1., -1.]])

In [63]:
# ceil
np.ceil(a)

array([[ 0.,  1.,  1.,  1.],
       [-0., -0., -0.,  1.],
       [ 1.,  1., -0., -0.]])

#### Indexing and Slicing

In [64]:
a = np.arange(10)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,2,2)

In [65]:
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [66]:
a[-1]

9

In [68]:
b[1,2]

6

In [69]:
c[0,1,1]

3

In [70]:
c[0][1][1]

3

In [71]:
a[2:5]

array([2, 3, 4])

In [72]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
b[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [74]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
c[:,1:,1:]

array([[[3]],

       [[7]]])

In [78]:
d = np.arange(27).reshape(3,3,3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [80]:
d[:,2:,2:]

array([[[ 8]],

       [[17]],

       [[26]]])

#### Iterating

In [81]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [82]:
for i in b:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [83]:
for i in d:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [85]:
for i in np.nditer(d):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#### Reshaping

In [86]:
# reshape

In [94]:
# Transpose
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [95]:
# Ravel
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Stacking

In [96]:
# horizontal
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)
np.hstack((a,b))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [97]:
# vertical
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Spliting

In [98]:
# horizontal
np.hsplit(a,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [99]:
# vertical
np.vsplit(a,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]