<a href="https://colab.research.google.com/github/San-desh17/Numpy/blob/numpy/Numpy_part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#### np.sort()

In [2]:
# python ko sort le list dinxa
# numpy ko sort le numpy array dinxa

In [7]:
a = np.random.randint(1,20,20)
a

array([ 5, 15, 10,  8,  6,  9, 15,  3, 13,  2,  5, 17, 18, 15,  6,  3,  1,
        7,  1,  8])

In [8]:
np.sort(a)

array([ 1,  1,  2,  3,  3,  5,  5,  6,  6,  7,  8,  8,  9, 10, 13, 15, 15,
       15, 17, 18])

In [13]:
np.sort(a)[::-1]

array([18, 17, 15, 15, 15, 13, 10,  9,  8,  8,  7,  6,  6,  5,  5,  3,  3,
        2,  1,  1])

In [9]:
b = np.random.randint(1,20,20).reshape(4,5)
b

array([[ 1,  3,  4,  9, 19],
       [ 2, 17, 13,  6,  2],
       [14, 18, 18, 15, 17],
       [ 5,  7,  9,  8,  2]])

In [11]:
np.sort(b,axis=0)

array([[ 1,  3,  4,  6,  2],
       [ 2,  7,  9,  8,  2],
       [ 5, 17, 13,  9, 17],
       [14, 18, 18, 15, 19]])

#### np.append()

In [14]:
b

array([[ 1,  3,  4,  9, 19],
       [ 2, 17, 13,  6,  2],
       [14, 18, 18, 15, 17],
       [ 5,  7,  9,  8,  2]])

In [16]:
np.append(b,np.random.randint(1,20,5).reshape(1,5),axis=0)

array([[ 1,  3,  4,  9, 19],
       [ 2, 17, 13,  6,  2],
       [14, 18, 18, 15, 17],
       [ 5,  7,  9,  8,  2],
       [ 6,  7, 15,  9, 12]])

#### np.concatenate()

In [17]:
c = np.arange(6).reshape(2,3)
c
d= np.arange(6,12).reshape(2,3)
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### np.unique()

In [19]:
e = np.random.randint(1,10,20)
e

array([1, 6, 2, 7, 7, 5, 9, 3, 9, 3, 7, 6, 2, 5, 8, 5, 1, 7, 8, 7])

In [20]:
np.unique(e)

array([1, 2, 3, 5, 6, 7, 8, 9])

#### np.expand_dims

In [21]:
a

array([ 5, 15, 10,  8,  6,  9, 15,  3, 13,  2,  5, 17, 18, 15,  6,  3,  1,
        7,  1,  8])

In [22]:
np.expand_dims(a,axis=0)

array([[ 5, 15, 10,  8,  6,  9, 15,  3, 13,  2,  5, 17, 18, 15,  6,  3,
         1,  7,  1,  8]])

#### np.where()

In [23]:
a

array([ 5, 15, 10,  8,  6,  9, 15,  3, 13,  2,  5, 17, 18, 15,  6,  3,  1,
        7,  1,  8])

In [24]:
np.where(a>10) # return index position

(array([ 1,  6,  8, 11, 12, 13]),)

In [25]:
# np.where(condition, True, false)
np.where(a>10,0,a)

array([ 5,  0, 10,  8,  6,  9,  0,  3,  0,  2,  5,  0,  0,  0,  6,  3,  1,
        7,  1,  8])

#### np.argmax

In [26]:
np.argmax(a) # index position

12

#### np.argmin

In [27]:
np.argmin(a)

16

#### np.cumsum

In [28]:
np.cumsum(a)

array([  5,  20,  30,  38,  44,  53,  68,  71,  84,  86,  91, 108, 126,
       141, 147, 150, 151, 158, 159, 167])

#### np.cumprod()

In [29]:
np.cumprod(a)

array([               5,               75,              750,
                   6000,            36000,           324000,
                4860000,         14580000,        189540000,
              379080000,       1895400000,      32221800000,
           579992400000,    8699886000000,   52199316000000,
        156597948000000,  156597948000000, 1096185636000000,
       1096185636000000, 8769485088000000])

#### np.percentile

In [30]:
np.percentile(a,75)

13.5

In [31]:
np.percentile(a,100)

18.0

#### np.histogram

In [33]:
np.histogram(a,bins=[0,5,10,15,20])

(array([5, 8, 2, 5]), array([ 0,  5, 10, 15, 20]))

#### np.corrcoef()

In [34]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

#### np.isin()

In [35]:
a

array([ 5, 15, 10,  8,  6,  9, 15,  3, 13,  2,  5, 17, 18, 15,  6,  3,  1,
        7,  1,  8])

In [37]:
a[np.isin(a,[10,15])]

array([15, 10, 15, 15])

#### np.flip()

In [38]:
np.flip(a)

array([ 8,  1,  7,  1,  3,  6, 15, 18, 17,  5,  2, 13,  3, 15,  9,  6,  8,
       10, 15,  5])

In [40]:
b

array([[ 1,  3,  4,  9, 19],
       [ 2, 17, 13,  6,  2],
       [14, 18, 18, 15, 17],
       [ 5,  7,  9,  8,  2]])

In [39]:
np.flip(b,axis=1)

array([[19,  9,  4,  3,  1],
       [ 2,  6, 13, 17,  2],
       [17, 15, 18, 18, 14],
       [ 2,  8,  9,  7,  5]])

#### np.put()

In [41]:
np.put(a,[0,1],[100,200])
a

array([100, 200,  10,   8,   6,   9,  15,   3,  13,   2,   5,  17,  18,
        15,   6,   3,   1,   7,   1,   8])

#### np.delete()

In [42]:
np.delete(a,0)

array([200,  10,   8,   6,   9,  15,   3,  13,   2,   5,  17,  18,  15,
         6,   3,   1,   7,   1,   8])

#### Set functions

In [43]:
# np.union1d

In [44]:
# np.intersect1d

In [45]:
# np.setdiff1d

In [46]:
# np.setxor1d

In [47]:
# np.in1d

#### np.clip()

In [48]:
np.clip(a,a_min=10,a_max=15)

array([15, 15, 10, 10, 10, 10, 15, 10, 13, 10, 10, 15, 15, 15, 10, 10, 10,
       10, 10, 10])

In [49]:
# np.swapaxes

In [50]:
# np. uniform

In [51]:
# np.tile

In [52]:
# np.count_nonzero

In [53]:
# np.repeat